### ISSUE TITLE
[Feature Request] Automatically reconnect after lost connection

### ISSUE THREAD

**Issue by MrCustomizer** [sandsmark/QuasselDroid#104]
I would really like to see an option which enables an automatic reconnect after the connection is lost. After every network change (wifi to mobile or vice versa) or after a period of poor/no mobile connection quasseldroid's connection to the core is lost and you have to manually open the application and hit "connect" to reconnect.

**Comment by kenborge** [comment]
This should be added in the beta version now, and in production soon

**Comment by binwiederhier** [comment]
Awesome! Thanks!

**Comment by Rush** [comment]
Can anybody share the beta builds? They seem to be behind the Google Plus wall.

**Comment by mrueg** [comment]
https://f-droid.org/repository/browse/?fdid=com.iskrembilen.quasseldroid
