### ISSUE TITLE
Quasseldroid crashes on connection; regular Quassel connects just fine.

### ISSUE THREAD

**Issue by aetherspoon** [sandsmark/QuasselDroid#105]
I'm running a Galaxy Nexus (stock GooPlay version) and, after upgrading to 4.3 from the OTA install, Quasseldroid crashes on connecting to my home QuasselCore. I've tried wiping settings from my phone and reinstalling Quasseldroid - no effect. I've submitted this via Android's crash report feature, but I wasn't sure if those got to you.

After further testing, it looks like the upgrade to 4.3 was a red herring; I still can't connect even after wiping my phone and installing the latest stable Cyanogenmod, so I'm assuming it is choking on something in my SQLlite database for Quassel.

What additional info do you need from me?

**Comment by kenborge** [comment]
What version are you using? If you're not in the beta, try this version https://www.dropbox.com/s/fqwpqw498fv19i9/QuasselDroid-release-0.11.5.apk?dl=0 and see if the problem is still there. A lot has changed in the beta compared to the production version now.

**Comment by YtvwlD** [comment]
@kenborge The problem is solved in v0.11.4 which I downloaded from F-Droid today.

**Comment by kenborge** [comment]
Counting this as fixed then
