### ISSUE TITLE
Crash while 'Receiving network' (Always, makes the app completely unusable.)

### ISSUE THREAD

**Issue by m-ou-se** [sandsmark/QuasselDroid#114]
When I connect, this happens every time:

"Connecting..." (~3 sec)
"Connection established, waiting on networks..." (~2 sec)
"Receiving network: OFTC" (~ 2 sec)
"Receiving network: EFnet" (~15 sec)
*crash*
The standard android crash window (with the 'report' button) pops up, but then goes away after just a second. (When I'm fast, I can still press the report button.)

I'm running Android 2.3 on a HTC Desire Z. Reinstalling or wiping user data doesn't help. I'm using Quassel every day on my laptop with the standard Quasselclient without a problem.

**Comment by kenborge** [comment]
If you're not in the beta, could you try one of the newer version found here https://www.dropbox.com/sh/uxpckeobyz612qj/j2k7QsU7xC and see if the problem is still there. At the time i am writing this the newest version is 0.11.5

**Comment by m-ou-se** [comment]
I have a new phone now with a lot more ram and the newest version of Android, and now everything works fine. I don't have the old phone anymore, so I can't really debug the original issue, as I can't reproduce it anymore. I guess this bug can be closed, if nobody else is experiencing the issue.

**Comment by justjanne** [comment]
Original author can not reproduce it
