### ISSUE TITLE
Quasseldroid crashing connecting to 0.9.1 core, ClassCastException Long cannot be cast to Integer

### ISSUE THREAD

**Issue by marsbard** [sandsmark/QuasselDroid#119]
I get this when trying to connect to 0.9.1 core. I know that others can connect to 0.9.1 so I'm not sure why this is happening

com.iskrembilen.quasseldroid,572996,java.lang.ClassCastException,java.lang.Long cannot be cast to java.lang.Integer,CoreConnection.java,392

**Comment by kenborge** [comment]
Make a new issue if the issue persists
