### ISSUE TITLE
Usability Issue: The Core/Account UI makes no sense

### ISSUE THREAD

**Issue by justjanne** [sandsmark/QuasselDroid#205]
The way the UI in the LoginActivity saves the core and identity makes no sense.

As userdata is remembered by being bound to the core, you need to add a new core to store a second identity.

It would be better if this could be somehow solved by adding proper account management to that UI.

**Comment by kenborge** [comment]
This is also the case with the PC client. Not sure it's a very common situation for someone to have multiple users on the same core

**Comment by justjanne** [comment]
On the PC client you have one window where you enter core, username, password.

In QuasselDroid on the other hand username, password and core data are seperated, making it seem like one could store multiple usernames and passwords per core.
