### ISSUE TITLE
Stay in the main activity when disconnected

### ISSUE THREAD

**Issue by zhaofengli** [sandsmark/QuasselDroid#242]
My 3G network is a bit wacky, and I often get disconnected while chatting. Currently the client sends you back to the login screen when the connection drops, which is not very intuitive. While I'm aware that all other Quassel clients do the same, why not improve usability and make QuasselDroid stay in the main activity when disconnected? The client can attempt to reconnect and append the new logs to the displayed buffer after the connection reestablishes.

P.S. The new material design rocks. One more reason to switch back from IRCCloud :)

**Comment by justjanne** [comment]
We were already discussing something like this, but sadly it is not possible without changes to the quasselcore itself yet.

**Comment by zhaofengli** [comment]
Out of curiosity, what's preventing this from being implemented? I see that every message is identified with a `messageid` in the `backlog` table, and we could skip fetching those that are already on the screen.

**Comment by ibex-are-goats** [comment]
Would it not be enough to just have QuasselDroid automatically reconnect?
