### ISSUE TITLE
Autocomplete mangles nicknames using TouchPal keyboard with prediction turned on

### ISSUE THREAD

**Issue by synrg** [sandsmark/QuasselDroid#244]
For months I've endured this and only just now realized the cause and discovered two workarounds. It is in all likelihood not a bug in QuasselDroid, but a limitation in how TouchPal prediction does its job. Filing this issue on QuasselDroid will at least make it possible for other users experiencing this issue to find it and work around it, even if you decide there's nothing you can do and just close it (which I would totally understand). But on the off chance you could come up with a cleaner workaround that unconfuses TouchPal prediction, I'd really appreciate if you could try to reproduce it and see if you can do anything to help.

When using the TouchPal keyboard with prediction turned on, pressing the magnifying glass to autocomplete a nick will initially autocomplete it correctly, e.g. "Nick" => "nickname: ". However, as soon as the next character is typed (any single character will do, e.g. 'x', or a swipe will produce the same result, only with the swipe prediction substituted for 'x') after the "nickname: " in the input area, the nickname becomes mangled in a very specific way: "nickname: " => "nicknamNickx", i.e. the last three characters ('e: ') are replaced by whatever was initially typed before pressing the icon to autocomplete it (in this example, "Nick"), followed by whatever new material was typed after the autocomplete occurs.

The bug does not occur always. Cases I've tested so far:

- If you press the autocomplete icon two or more times, the bug does not occur.

Workarounds:

- If you toggle prediction off, the bug does not occur.
- This bug does not affect the default AOSP keyboard.
- I have not tested if the bug exists with any other keyboards that have prediction, or if the same workaround would help.

The workarounds are a bit of a hassle to use. It means doing without features when using QuasselDroid that make using a keyboard on a mobile device more pleasant. However, if there's nothing else that can be done, I'll somehow come to terms with it. :)

Thanks,
Ben

**Comment by justjanne** [comment]
Will have to do further investigation into this in the next days.

**Comment by synrg** [comment]
I don't recall having the issue recently, so I tried my steps above to reproduce it just now and could not reproduce the problem anymore. Please just close the issue. Thanks.
