### ISSUE TITLE
QuasselDroid doesn't play fairly with Android memory management?

### ISSUE THREAD

**Issue by ibex-are-goats** [sandsmark/QuasselDroid#246]
I was paying attention to Android 5.1 memory usage and I noticed that QuasselDroid was my only user application which never allowed itself to be sent to cache or paged to disk. It was always a running server (even though it's a client ;) if my nomenclature is correct) Is this known?

I do like QuasselDroid being high priority in memory so I don't need to manually reconnect upon running a new instance. But Android 5.1 manages memory very well on its own, and it cares which applications you use often and leave present in the multitasking view. It will keep a program running if you keep using it like I use QuasselDroid. But it will also kill that program if you've suddenly got 300MB of web browsing happening and need the extra memory ;) Whereas right now, QuasselDroid is ALWAYS a running server.

On my phone I need every MB of memory efficiency I can reclaim. What say you?

I think if the fate of the QuasselDroid backend is tied to the fate of the front-end, all will be well. If you're worried about QuasselDroid being forced closed by Android, maybe an instant-reconnect feature upon running QuasselDroid would make it act as if it never closed in the first place.

Thanks for the good work! PS: I am proud to use F-Droid to download open source apps including QuasselDroid!

**Comment by justjanne** [comment]
QuasselDroid needs to stay connected all the time to get highlight notifications, etc – I hope this cleared your question.

**Comment by sandsmark** [comment]
what janne said, and "instant reconnect" won't work for obvious reasons (connecting sometimes takes a looong time)

**Comment by ibex-are-goats** [comment]
I get notifications from applications that don't stay open all the time. Presumably they do this by turning on and off periodically?

Using the Developer Options -> Process Stats tool (more: http://android-developers.blogspot.ca/2014/01/process-stats-understanding-how-your.html ) I can see that the Quasseldroid front end is active as much as any other social app, but that the backend service is active 94% of the time! This is atypical for an application on my device.

**Comment by sandsmark** [comment]
this is a direct effect of how the (current) quassel protocol works.
