### ISSUE TITLE
Feature Request: A fully armed and operational battlewidget

### ISSUE THREAD

**Issue by ibex-are-goats** [sandsmark/QuasselDroid#247]
I like having prominent application windows right on the android home screen. Example: Gmail widget.

Other mobile operating systems have attempted such a scheme in the past, where you swipe left and right to view your primary applications. I like it. It works well. But few applications support this use case.

I would like a fully armed and operational QuasselDroid widget on the home screen! ;)

**Comment by heftig** [comment]
Might be worth implementing the Chat Monitor as a widget.

**Comment by ibex-are-goats** [comment]
I do still want this! ;)

**Comment by justjanne** [comment]
@ibex-are-goats sure, just, this app isn’t maintained anymore and has been replaced, the new app (and its issue tracker) live at https://git.kuschku.de/justJanne/QuasselDroid-ng/issues (login with GitHub is supported)
