### ISSUE TITLE
Day changed events are not displayed

### ISSUE THREAD

**Issue by Scheirle** [sandsmark/QuasselDroid#248]
Probably because of a missing `break;` [here](https://github.com/sandsmark/QuasselDroid/blob/master/QuasselDroid/src/main/java/com/iskrembilen/quasseldroid/gui/fragments/ChatFragment.java#L704).

**Comment by justjanne** [comment]
1. Thanks for finding that missing break
2. Sadly, that is not the issue – the issue is that Day Change events have to be injected into the message list by the client, which quasseldroid doesn’t support yet.
