### ISSUE TITLE
Kick Message incorrectly displayed with 'Show User Hostnames' enabled

### ISSUE THREAD

**Issue by mschatz56** [sandsmark/QuasselDroid#256]
I have 'Show User Hostnames' for server messages enabled.
The Kick message reads:
"nick1 has kicked nick2 (user1@host1) from #chan (reason)"

The 'user@host' portion should be moved over to 'nick1'. I don't believe the server even sends a user@host for the nick being kicked, only the kicker.

**Comment by justjanne** [comment]
Should be fixed now – I mean, I moved the message around
