### ISSUE TITLE
Add support for Pebble smartwatch

### ISSUE THREAD

**Issue by kipe** [sandsmark/QuasselDroid#258]
It would be great to have support for Pebble.
I made an quick hack: https://github.com/kipe/QuasselDroid/commit/7046344154b831bed8a34700f9a3ffdc768031a6, which proves that the support shouldn't be that hard to implement. I'm very unexperienced with Android coding at the moment, so I have no means to take this much further, at least not at the moment.

At the moment the features and/or issues include:
- Send highlights as notifications to Pebble (not sure if done correctly / in the correct location)
- ~~The Pebble support should have an item in settings, however I didn't figure out how to do it correctly.~~
- Notification is sent on each message (even if the buffer is open and visible, configurable in settings?)

So, any help and suggestions are more than appreciated, I'm more than willing to work on this to get Quassel to my wrist :smile: 

//E: Well, adding the settings -item wasn't that hard: https://github.com/kipe/QuasselDroid/commit/b6400756d0758eb8fc3a6e348cd56d78c91498e4

**Comment by justjanne** [comment]
I’d suggest you to just open a pull request – this looks very nice, and should work (I can’t test it myself currently, as I own no pebble smartwatch).

**Comment by kipe** [comment]
Well, that's always good to hear :smile: 

I'll test this out at least for today, to see that there's no strange bugs when reconnecting etc and do the PR in the evening, if no such bugs are found...

**Comment by kipe** [comment]
As I thought, there's issues when reconnecting to core. For some reason, it sends random messages from the past. I'm running quite an old core, so I should try updating that first to see if the issue comes from the core...

**Comment by justjanne** [comment]
Ah, yeah, that issue is known.

Just add a check to make sure the initialization phase is already over.

**Comment by kipe** [comment]
So something in the lines of https://github.com/kipe/QuasselDroid/commit/06a7289cd9533e66d449a394adad47b449bf51c2?

At least seems to work with a quick test. As before, I'll rather test for one working day to see how it behaves before submitting a PR.

**Comment by kipe** [comment]
Well, just noticed https://github.com/sandsmark/QuasselDroid/commit/95f1161453924eaa7df2a549a7ad35ebeab8ecf1, which takes care of this... Pulling back my own hack and using this one instead.
