### ISSUE TITLE
Option to upload images to imgur or similiar

### ISSUE THREAD

**Issue by duramato** [sandsmark/QuasselDroid#259]
Something like IRCCloud has where you input the login details on the settings and you can take a pic or upload one from the library to there and it will be linked in the irc chat

**Comment by fernandog** [comment]
+1

**Comment by duramato** [comment]
Example SS
![screenshot_2015-11-17-14-15-35](https://cloud.githubusercontent.com/assets/10121067/11213917/8c510680-8d36-11e5-8cef-a9786f40bee7.png)
