### ISSUE TITLE
Option to upload pastes to Pastebin or similiar

### ISSUE THREAD

**Issue by duramato** [sandsmark/QuasselDroid#260]
Something like IRCCloud has where you can upload pastes to pastebin,it could also be uploaded as a gist or pastebin and be shared on the current channel

**Comment by fernandog** [comment]
+1

**Comment by duramato** [comment]
Thats what i also had on my mind, On IRCCloud if you paste something with multiplle lines it prompts you if you whant to upload as a paste ,to their own paste service or pastebin

**Comment by duramato** [comment]
Example SS
![screenshot_2015-11-17-14-15-35](https://cloud.githubusercontent.com/assets/10121067/11213917/8c510680-8d36-11e5-8cef-a9786f40bee7.png)
