### ISSUE TITLE
Avoid multiple client notifications. For example when buffer is open in desktop don't notify mobile

### ISSUE THREAD

**Issue by fernandog** [sandsmark/QuasselDroid#261]
Like the title

**Comment by romibi** [comment]
log from irc:
>\<justJanne\> **if a the core would allow clients to say "hey, I have this buffer open"**
>\<justJanne\> and tell that to other clients
>\<justJanne\> then QD could see "oh, another client has this open, don’t mark it as notification"
>\<izzy84075\> Mmm... Possibly, yeah. That's a Core change, though.
>\<justJanne\> that’s why I’ll tag fernandog’s issue with "requires core changes"
>\<justJanne\> and then I’ll forget about it for now
>\<izzy84075\> Ah, heh.
>\<fernandog\> lol. i got two notifications: desk and QD
>\<romibi\> **or if more than 1 client connected wait for notification something like 2*RTT (wouldn't require core change)**
>\<izzy84075\> Ah, that's another wait to do it.
>\<izzy84075\> s/wait/way/
>\<justJanne\> well, not really
>\<justJanne\> what if client A as RTT of 20ms, client B has RTT of 200ms
>\<justJanne\> (lan with fiber vs. shitty 2G in subway)
>\<romibi\> quasseldroid has mostlikely the shittier connection ... wouldn't solve the problem completely but minimize it
>\<justJanne\> well, write the ideas in the issue report

or 3*RTT or something ...

**Comment by fernandog** [comment]
IMHO i think "if a the core would allow clients to say "hey, I have this buffer open" it's the best solution
