### ISSUE TITLE
Don't close the chats when disconnected from core

### ISSUE THREAD

**Issue by MyIgel** [sandsmark/QuasselDroid#273]
While travelling by train the mobile connection drops every minute, and when it comes back it is really slow; that means that I am unable to read any messages  what is really frustrating.
Is it possible to keep the chats open and silently try to reconnect in the background?

**Comment by justjanne** [comment]
This feature has been asked for for a long time, and it’s why I am working on a new version that will provide that feature – but a lot of work is required for that, so it’s been going on since November.

**Comment by dabukalam** [comment]
Is there a list of tasks for this somewhere?

**Comment by Georgeto** [comment]
@justjanne Did you make progress implenting this feature? I am also on a train right now ;)
