### ISSUE TITLE
Timestamp format is undocumented and unverified

### ISSUE THREAD

**Issue by ShadowNinja** [sandsmark/QuasselDroid#275]
I first tried something like "YYYY-MM-DD HH:mm:SS".  That was accepted, but then the app crashed when opening a buffer.  I then tried strftime format, but that also failed.  I found out from IRC that it apparently uses Java's [SimpleDateFormat](http://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html).

The format should be documemted in the app and then verified, instead of crashing obscurely when opening a buffer.

**Comment by wolfpackmars2** [comment]
Appears that the Qt format is used.

https://doc.qt.io/Qt-5/qdatetime.html#toString
