### ISSUE TITLE
Nick list blocks ability to long-press in text input box when too close to the edge of screen.

### ISSUE THREAD

**Issue by dabukalam** [sandsmark/QuasselDroid#277]
When I've typed a message I want to send and want to paste a link, I have no way of doing that without pasting the link first then typing the message afterwards, as once enough words have filled the input box trying to press will just bring the nick list up.

**Comment by justjanne** [comment]
The issue has been known for quite a while, and has been fixed in the alpha of the new release ( see justJanne/QuasselDroid-ng )

**Comment by dabukalam** [comment]
Thanks @justjanne I will try that.
