### ISSUE TITLE
Anti feature: Mandatory and non configurable error reporting

### ISSUE THREAD

**Issue by TheAssassin** [sandsmark/QuasselDroid#282]
First of all, I love QuasselDroid, you guys did a great job creating a usable Quassel client for Android.
But I recently had one or two crashes (shit happens) and discovered a little popup message that disappears again a few hundred ms after, telling me something about the app sending a crash log to some server without me having a chance to intervene.
I tried to find an option to disable this behaviour, as it is generally not recommended to use this for a user (yeah, I know it might be useful for you, but I love my privacy), but apparently there's no such possibility.

So I thought I'll file an issue with your repository to get in touch with you about this. The message of this issue is: **Please change your app to respect users' privacy**. I know I could change it by compiling my own version of the app, but why not get in touch with you and discuss the issue to fix it for everyone.

My personal opinion on such stuff is "make it opt-in". At some other app projects, the app prompts the user to choose whether to report the issue (which leads to composing a mail the user can send to us, containing all the details that would be sent, being 100% transparent to the user) or otherwise dismiss the crash report. We receive about 1000 mails a month with crash information.

I thought I'd first try to convince you guys of making it opt-in, or at least opt-out. It must be a user's choice whether to send such data to you or not. It is a serious anti-feature to have it opt-out, but even worse having no chance to deactivate it.

Talking about anti-feature: I feel responsible to report this to F-Droid store, too, as their guidelines about anti-features are very clear on this kind of privacy issue: Quasseldroid definitely deserves the Tracking flag if this won't be changed to opt-in.

> ‘Tracking’ - the application tracks and reports your activity to somewhere without your consent. It’s commonly used for when developers obtain crash logs without the user’s consent, or when an app is useless without some kind of authentication.
>
> -- https://f-droid.org/manual/html_node/AntiFeatures.html

So the best suggestion I could make is adding an option in the app's preferences where you can switch on the crash reporting. The second best thing I can suggest is implementing the same way I described: Just show a little modal dialog informing about the crash, and what information would be sent to your servers, above a confirm and dismiss button.

Another way would be adding an opt-out option in the preferences. This is pretty much the same approach as the first suggestion but you'd switch the button on by default. Unfortunately, QuasselDroid would have to get the Tracking flag then too.

Just for comparison: Another popular app that has received a Tracking flag was the Android version of Firefox, because their crash reporter was switched on by default, too.

**Comment by justjanne** [comment]
Actually, this is already a thing – and the update was deployed to F-Droid and the Google Play Store already, but it seems like it was never received, for some reason. (I’ve been looking into that).

The version with the reporter running by default was never meant to be released outside of the debug APK downloads, and, as said before, was already meant to be replaced.

The current solution is that, on first start, or first start after an update, the user gets a message informing them of the reporter, and asks them to accept it, or change it, before they can use the app.

**Comment by TheAssassin** [comment]
Sounds good, after a little discussion on IRC I'm pretty sure this can be resolved. Closing for now.
