### ISSUE TITLE
Certain colours have very low contrast against the dark theme

### ISSUE THREAD

**Issue by Alexendoo** [sandsmark/QuasselDroid#292]
An update hit the play store the other day that changed the nick colours, however some of them don't get on well with the dark theme

![screenshot_20171223-112851](https://user-images.githubusercontent.com/1830331/34319227-89f3e2c2-e7d4-11e7-8fc2-6f4460a3b00f.png)

(numbers are arbitrary)

**Comment by justjanne** [comment]
Since this update, Quasseldroid will use whatever colors are defined as standard by the Quassel team. Please open an issue with them.

**Comment by Alexendoo** [comment]
This is not an issue for the Quassel team as they do not ship a dark theme with those foreground colours, Quasseldroid however does.

**Comment by digitalcircuit** [comment]
I've noticed that as well; the new colors are easier to read in Quassel and Quasseldroid's light theme, but make the dark theme worse.  *Disclaimer: I [contributed the new colors upstream](https://github.com/quassel/quassel/pull/266 ).*

The next-generation Quasseldroid will have a better theming engine that should be able to change nick colors, too.  If you're willing to wait a while longer (unsure of how much longer), this should be addressed then.
