### ISSUE TITLE
"Receiving buffer list information" notification after reconnect never goes away

### ISSUE THREAD

**Issue by BaronKrause** [sandsmark/QuasselDroid#295]
After you connect to a core and then get disconnected for whatever reason, when you reconnect you get a notification in the system tray about "Receiving buffer list information" that never goes away until you close the app.

If you were to close the app after it disconnected from the core and then opened and connected again, there will be no notification. This only happens when you reconnect without closing the app, but it will happen every time. It still works, just you have that notification.

I'm using a Nexus 6P on Android 8.1, and can verify it happened at least on 8.0 as well.

It's not a big deal, but figured it wasn't an intended behavior.

**Comment by justjanne** [comment]
We’re currently working on a significantly improved version of Quasseldroid. It is available under the alpha version link at https://quasseldroid.info/releases/. Please verify that your bug still exists with that version (it installs in parallel to Quasseldroid). Currently, the existing version of Quasseldroid will only get bugfixes for major bugs, the focus is on finishing this new version instead.
