### ISSUE TITLE
Cannot connect after recreating certificate

### ISSUE THREAD

**Issue by emil-nasso** [sandsmark/QuasselDroid#77]
I had some issues with my quassel core so i recreated the certificate using the wiki suggested method: `openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout ~/.config/quassel-irc.org/quasselCert.pem -out ~/.config/quassel-irc.org/quasselCert.pem` 

After doing this i got an "Connection failed" every time i tried to connect to my core. Removing the "core-configuration" from quassel droid and adding it again didnt help. Neither did upgrading the application to the latest version.

Completely uninstalling the application and installing it again from android maket fixed the issue.

Should i supply any more information?

**Comment by kenborge** [comment]
Should be fixed
