### ISSUE TITLE
[Feature Request] Options to disable time stamps and other minor UI tweaks.

### ISSUE THREAD

**Issue by mattconsto** [sandsmark/QuasselDroid#90]
I really like this application but on my rather low resolution android phone, you cannot see as much of the chat as I would like to due to the time stamp and name takes up ~ 1/2 the screen width. An option to remove the time stamp and an extra small font would be amazing on low res devices.

Also, one nice feature about the desktop quassel client is the fact that all the chat lines up regardless of nickname length. Maybe implementing that with the option to turn it on and off?

One more UI tweak that again, would be nice on smaller resolution phones would be the option to move the Channels, Chat and Nicks slider into the drop down thing. Along with the option to hide the topic.

Thanks for the great app and I hope it becomes even better.

**Comment by kenborge** [comment]
Timestamp can now be hidden and the nickname line up is also changed
