### ISSUE TITLE
Default/Global settings for hiding events

### ISSUE THREAD

**Issue by ayonix** [sandsmark/QuasselDroid#93]
In my opinion it would be nice to have global or default hidden events and not only for every buffer.

**Comment by flasheater** [comment]
+1
I don't even know how to hide those in one buffer...

**Comment by justjanne** [comment]
@flasheater There is a button with a tag symbol, labeled as "Hide Events" in the ActionBar

But right now you can’t set a default value, true.

**Comment by flasheater** [comment]
Ah, don't know how I could have missed it. Anyways, I'd even go so far as saying that all event messages should be hidden by default. I don’t see the use case,  especially on mobile.

**Comment by toXel** [comment]
+1
